// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CognitoAuth: typeof import('./components/CognitoAuth.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Email: typeof import('./components/Email.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GoogleAuth: typeof import('./components/GoogleAuth.vue')['default']
    Ico: typeof import('./components/Ico.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
